admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /ufgadmin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"