# do not change these lines: 'parameters' and 'languages'
parameters:
    languages:
        ge:
            name: Georgian
            title: ქართული
            prefix: ge
            enabled: 1
        en:
            name: English
            title: English
            prefix: en
            enabled: 1
        ru:
            name: Russian
            title: Русский
            prefix: ru
            enabled: 1

    languages.locales: [ge, en, ru]
    languages.default: ge